version: 0.2

phases:
  install:
    commands:
      - echo " - Installing poetry"
      - pip install poetry
  pre_build:
    commands:
      - echo " - Installing package"
      - poetry install --with dev
      - echo " - Running tests"
      - poetry run pytest
  build:
    commands:
      - echo " - Building package"
      - poetry build
      - echo " - Building container"
      - docker build . -t tester

#      - cp hello_world/*.py hello_world/build/
#      - echo "Starting SAM packaging `date` in `pwd`"
#      - aws cloudformation package --template-file template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yaml
#  post_build:
#    commands:
#      - echo "SAM packaging completed on `date`"

#artifacts:
#  files:
#    - packaged.yaml
#  discard-paths: yes

#cache:
#  paths:
#    - '/root/.cache/pip'